apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: faster
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
spec:
  ports:
  - port: 80
  selector:
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
      tier: frontend
  template:
    metadata:
      labels:
        app: mediawiki
        tier: frontend
    spec:
      imagePullSecrets:
      - name: local-registry
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: mediawiki
        image: 10.128.0.4:5000/frontend:1
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d